### ISSUE TITLE
No prebuilds for Linux kernel 4

### ISSUE THREAD

**Issue by romash1408** [extremeheat/node-raknet-native#5]
In my debian system `os.release()` returns `4.19.0-8-amd64` and there is no prebuilds for `linux-4-x64` :(

**Comment by romash1408** [comment]
Built from current master
[raknet-prebuild-linux-4-x64.node.zip](https://github.com/extremeheat/node-raknet-native/files/7636069/raknet-prebuild-linux-4-x64.node.zip)

**Comment by extremeheat** [comment]
So with respect to this I would prefer if there a way to automate this build process like we have now. It's not really sustainable manually uploading prebuilds like this. If there was some way we could do this on CI, that would be good. The CI makes prebuilds for all the OSes supported by Github Actions so that is a limiting factor at the moment
